-- =============================================================================
-- ReceptCar — Phase 3 : renforcer la valeur de preuve de la fiche PDF
-- Non destructif : nouvelles colonnes uniquement, valeurs par défaut NULL ou
-- calculées automatiquement (numéro de fiche), aucune donnée existante
-- modifiée ni supprimée.
-- =============================================================================

-- Coordonnées du garage, affichées dans l'en-tête du PDF.
alter table public.garages add column if not exists phone text;
alter table public.garages add column if not exists email text;

-- Numéro de fiche unique et lisible (affiché sur le PDF, utile en cas de
-- litige). Colonne "identity" : Postgres backfille automatiquement les
-- fiches déjà existantes dans leur ordre de création.
alter table public.receptions add column if not exists reception_number bigint generated by default as identity;

-- Niveau de carburant constaté à la réception.
alter table public.receptions add column if not exists fuel_level text
  check (fuel_level in ('empty', 'quarter', 'half', 'three_quarter', 'full'));

-- Photo du tableau de bord (kilométrage, voyants) à la réception.
alter table public.receptions add column if not exists photo_dashboard_path text;

-- Empreinte SHA-256 du PDF généré, pour détecter toute altération ultérieure.
alter table public.receptions add column if not exists pdf_sha256 text;

NOTIFY pgrst, 'reload schema';
